config/routes.rb
Rails.application.routes.draw do
  resources :tweets 
  root to: "tweets#index"
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def create
    tweet = Tweet.new(tweet_params)
    if tweet.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to :action => "show", :id => @tweet.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    Tweet.find(params[:id]).destroy
    redirect_to action: :index
  end

  private
  def tweet_params
    params.require(:tweet).permit(:body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geektwitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body, :size => 140 %> 
  <%= f.submit "編集する" %>
<% end %>

app/views/tweets/index.html.erb
<h1>掲示板</h1>
<h3>Tweet一覧</h3>
<%= link_to "新規投稿へ", new_tweet_path %>
<div class="tweets-container">
  <% @tweets.each do |t| %>
  <div class="tweet">
    <%= t.body %>
    <%= t.created_at %>
    <%= link_to "詳細へ", tweet_path(t.id) %>
    <%= link_to "編集する", edit_tweet_path(t.id) %>
    <%= link_to "削除する", tweet_path(t.id), method: :delete %>
  </div>
  <% end %>
</div>

app/views/tweets/new.html.erb
<h1>掲示板</h1>
<h3>新規Tweet</h3>
<%= form_for @tweet do |f| %>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :body, :size => 140 %>
  </div>
  <%= f.submit "Tweetする" %>
<% end %>
<%= link_to "Tweet一覧に戻る", tweets_path %>

app/views/tweets/show.html.erb
<h1>掲示板</h1>
<h3>Tweet詳細</h3>
<div class="tweet">
  <p><%= @tweet.body %></p>
  <p><%= @tweet.created_at %></p>
  <%= link_to "編集する", edit_tweet_path(@tweet.id) %>
</div>

<%= link_to "Tweet一覧に戻る", tweets_path %>